demo/urls.py
from django.urls import path
from . import views

app_name = "demo"

urlpatterns = [
    path('', views.home, name='home'),
    path('categories/', views.category, name='categories'),
    path('product-by-category/<slug:category>/', views.product_by_category, name='product_by_category'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include('demo.urls', namespace='demo')),
]

demo/views.py
from django.shortcuts import render
from inventory import models


def home(request):
    return render(request, 'index.html')


def category(request):

    data = models.Category.objects.all()

    return render(request, 'category.html', {"data": data})


def product_by_category(request, category):

    data = models.Product.objects.filter(category__slug=category).values(
        "id", "name", "slug", "category__name", "product__store_price",
        "product__product_inventory__units"
    )

    return render(request, 'product_by_category.html', {"data": data})


def product_detail(request, slug):

    filter_args = []

    if request.GET:
        for value in request.GET.values():
            filter_args.append(value)

    print(filter_args)
    # from django.db.models import Count

    print(models.ProductInventory.objects.filter(product__slug=slug))

    # Returns the Default Product for all ProductInventory Tuples
    # See ProductInventory Model for more detail
    data = models.ProductInventory.objects.filter(product__slug=slug).filter(
        attribute_values__attribute_value__in=filter_args
    ).values(
        "id", "product__name", "sku", "store_price", "product_inventory__units"
    )

    return render(request, 'product_detail.html', {"data": data})

demo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</head>

  <body>
    {% block content %}{% endblock content %}
  </body>
</html>

demo/templates/category.html
{% extends 'base.html' %}
{% block content %}
<h1> Categories </h1>
{% for x in data %}

    <a href="{% url 'demo:product_by_category' category=x.slug %}">{{x.name}}<a>

{% endfor %}
{% endblock content %}

demo/templates/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Index Page</h1>
<a href="categories/">Categories</a>

{% endblock content %}

demo/templates/product_by_category.html
{% extends 'base.html' %}

{% block content %}
<h1> Products </h1>
<ul>
{% for x in data %}

    <li>{{x.name}} [<a href="{% url 'demo:product_detail' slug=x.slug %}">View</a>]</li>
    <li>{{x.id}}</li>
    <li>${{x.product__store_price}}</li>
    <li>Stock Left - {{x.product__product_inventory__units}}</li>

{% endfor %}
</ul
{% endblock content %}

demo/templates/product_detail.html
<h1>Product Detail</h1>
{% extends 'base.html' %}


{% block content %}
<ul>
{% for x in data %}
    <li>{{x.product__name}} - {{x.sku}}</li>
    Stock Left - {{x.product_inventory__units}}
{% endfor %}
</ul>
{% endblock content %}